### ISSUE TITLE
Own/foreign Ansible playbooks

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#100]
Add an option to run own/foreign playbooks for a customized setup.

**Comment by jkrue** [comment]
How much Ansible should BiBiGrid support ?
- as whole playbook, completes roles or single tasks
- separated for master / worker and/or for all instances
How should such a ansible snippet packaged ? As Zip ? Is there a standard ?

Independent how we integrate this feature, it must be well documented (with examples)

**Comment by awalende** [comment]
My proposal would be the following:
Give Support for Roles and single Playbooks.
For this I'd give an option to include a path to an optional "ansible folder", which can contain Roles and/or Playbooks in the bibigrid.conf.

Playbooks are strict .yml and Roles are strict .tar.gz.

Including playbooks should be straight forward. Only requirement for them is, that they are targeting master and slaves hosts.

Roles would be a little bit more tricky. Packaging them to tar.gz makes them installable via ansible-galaxy cli. They will get globally installed and therefore easily includable in (main) playbooks. This is all nice, but where do we include the information on which host (master/slave) each role will be installed. Include an additional site.yml into the tar.gz archive?


This would definitaly need a guide/tutorial.

**Comment by jkrue** [comment]
We will add support for ansible-galaxy roles and local roles. The configuration must be extended to support this feature:
```
galaxy_roles:
  - role: <Name of the ansible galaxy role, e.g. geerlingguy.mysql>
    scope: one of "master", "slave" or "all"
    vars:
         key 1: value 1
         key 2: value 2
         ...
         key n : value n
   - role: ...

roles:
  - role: <name of the role>
    # on of file, url or git must be set
    file: < point to an local available zipped role >
    url: < point to an available zipped role>
    git:  < git repository containing a role>
    scope: one of "master", "slave" or "all"
    vars:
         key 1: value 1
         key 2: value 2
         ...
         key n : value n
   ...
```
