### ISSUE TITLE
Gridengine problem with number of dynamic event clients  

### ISSUE THREAD

**Issue by andreashoek** [BiBiServ/bibigrid#104]
Hey,

we're using BiBiGrid combined with the Gridengine (OGE) & ran into problems due to the limitation of the number of dynamic event clients (jobs submitted via qsub sync):

When submitting a higher number of qsub sync jobs (probably around a couple of hundred jobs in parallel) some of them fail with the error message 'Unable to initialize environment because of error: range_list containes no elements'.
It seems that this problem could be solved by changing the '**qmaster_params**' from '**none**' to **MAX_DYN_EC=X** (e.g. 1000 jobs in parallel). However, it seems that this can only be changed using the qconf -mconf option which only allows to change the configuration via an interactive editor.

Is there a way to change the default qmaster_params value before the cluster / Gridengine is launched?

Best,
Andreas

**Comment by jkrue** [comment]
There is unfortunately currently no option to change the default qmaster_params. But I think this is relative easy to integrate. We will hopefully integrate this into the next minor release ...

**Comment by jkrue** [comment]
The configuration should offer the following possibilties:

```
oge_conf:
        key 1: value1
        key 2: value2
        ...
        key n: value n
```

The keys overwrites the values in the gridengines master configuration if set.
