### ISSUE TITLE
Evaluate Theia-IDE as alternative web ide

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#107]
Cloud9 is a nearly perfect solution for an web ide. But since cloud9  is part of AWS we are searching for an (open source) alternative - the future of the cloud9 sdk outside the AWS ecosystem is absolute unclear.
[Theia IDE](https://www.theia-ide.org) seems to be an alternative. The docker container is small (about 69 MB) and runs very smoothly.

**Comment by jkrue** [comment]
In our case the docker container is nice for testing purpose, but not really an option since Theia-IDE should be used as kind of  desktop replacement for cloud instances.  The terminal (and everything else) should control the whole instance (and not only a containerized part of it). The following commands builds and install a (customized) Theia-IDE on a Ubuntu 18.04 (cloud) image
```
sudo apt-get install python make g++
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
source ~/.bashrc
nvm install 8
npm install -g yarn
mkdir my-app
cd my-app
cat << "END" >package.json
{
  "private": true,
  "dependencies": {
    "typescript": "latest",
    "@theia/typescript": "next",
    "@theia/navigator": "next",
    "@theia/terminal": "next",
    "@theia/outline-view": "next",
    "@theia/preferences": "next",
    "@theia/messages": "next",
    "@theia/git": "next",
    "@theia/file-search": "next",
    "@theia/markers": "next",
    "@theia/preview": "next",
    "@theia/callhierarchy": "next",
    "@theia/merge-conflicts": "next",
    "@theia/search-in-workspace": "next",
    "@theia/json": "next",
    "@theia/textmate-grammars": "next",
    "@theia/mini-browser": "next"
  },
  "devDependencies": {
    "@theia/cli": "next"
  }
}
END
yarn
yarn theia build
yarn theia start ~ --hostname localhost --port 8080
```

**Comment by jkrue** [comment]
I create a [ansible](role https://github.com/jkrue/theia-ide) for Theia-Ide, which works fine running Ubuntu 16.04/18.04. Theia-ide has one big advantage above Cloud9 : autosave functionality  :-)

@tdilger : Please test it and let me know what you think about it.

**Comment by tdilger** [comment]
Evaluated Theia IDE as a good alternative to Cloud9
