### ISSUE TITLE
Dynamically scale  depending on cluster load

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#117]
BiBiGrid does currently not support dynamically scale a running cluster depending on cluster load.
We have to solve some problems to implement it:
- Security. With the current approach there is no need to store the users cloud credentials in a cloud instance, everything concerning the virtual hardware is controlled  by BiBigrid running on the user local machine.
- At what time is a cluster _unused_ ? The scale mechanism must triggered by the user ("Scale down to only running the master") or needs information about the queues. Later one limits the feature to only directly supported grid batch systems (gridengine or slurm).
- Dynamic scaling is not supported very well by current grid batch systems. Slurm seems to be better in point than gridengine.

Since this feature needs a fundamental restructuring we could split this issue into parts.
1. Allow manually scale up/down 
2. Dynamically scale

**Comment by jkrue** [comment]
I made some extensive tests with current state of this branch:

1. If I try to terminate the cluster, I get a repeating warning : `WARN : Security group id should be uuid Trying again ...`. There is no difference in terminating an old (existing) cluster or fresh one

1. Zabbix doesn't work ...  This issue is already fixed in the development branch by @awalende. 

1. The new functions scaleUp and scaleDown works very well and stable (when using SLURM). The execution of the ansible task however is still missing.
   * ScaleDown: The slurm task must executed on the master : `ansible-playbook -i ansible_hosts -t slurm -l master  site.yml`
   * ScaleUp: The slurm task must also executed on the master. Additionally the full playbook must be executed on the new worker nodes. Lazy call : `ansible-playbook -i ansible_hosts -l workers site.yml`, better (and faster): `ansible-playbook -i ansible_hosts -l <ip-worker1>,<ip-worker2>,<ip>,...  site.yml`
1. ScaleUp does not respect the original cluster limit. This behaviour is fine for manually scaling (because the user hopefully knows what he is doing), but when implementing autoscaling any limits should be considered (not part of this issue though)
1. ScaleDown returns an error when I try to terminate more worker nodes  than currently exists. It would be nice if the number of running worker nodes is also mentioned in the error message.

@tdilger  Good work so far!

**Comment by tdilger** [comment]
Manual Scaling is done as described in [README](https://github.com/BiBiServ/bibigrid/blob/development/docs/README.md) and supports  
`bibigrid -su <cluster-id> <worker-batch> <count>` as well as  
`bibigrid -sd <cluster-id> <worker-batch> <count>`

Dynamically Scaling, however, needs further exploration and will be integrated in future versions

**Comment by jkrue** [comment]
[Slurm](https://slurm.schedmd.com) supports [elastic computing](https://slurm.schedmd.com/elastic_computing.html) as result of [Slurms integrated power saving mechanism]( https://slurm.schedmd.com/power_save.html).
