### ISSUE TITLE
GridEngine support

### ISSUE THREAD

**Issue by a1an77** [BiBiServ/bibigrid#136]
I noticed the warning about GridEngine deprecation and imminent support discontinuation. Why would that system not be supported anymore? When should we expect discontinuation? Since it would mean modification of our pipeline to switch to another engine it would be nice to have it also supported in future if possible.

**Comment by jkrue** [comment]
The GridEngine coming with Ubuntu 16.04  is a slightly modified version of the latest open source version (OGE) of the Sun GridEngine (SGE 6.2u5 from 2010). After  Sun was sold,  Oracle discontinued the GridEngine product and sold the product to Univa (now called Univa Grid Engine). There is  a community fork of the gridengine called [Son of a Gridengine](https://arc.liv.ac.uk/trac/SGE), but this seems to be dead ... the latest entries are from 2016.

The OGE however has some  dependencies which are not fulfilled by current distributions (e.g. Java 5). Curiously enough the packages of the OGE are still part of Ubuntu 18.04 and Debian 9, but the Grid Engine master crashes when I try to start it. I also tried to build the GridEngine from source, this works with a lot of manual adjustment, but no one knows how long and it was a pain in the ass.

This was the reason to discontinue the GridEngine support for recent distribution. As long Ubuntu 16.04 is official supported by Canonical (approx. April 2021) we will also support the GridEngine for Ubuntu 16.04.

Slurm is a good replacement (my opinion) for the GridEngine and is part of all major distributions. If you use the GridEngine cmdline scripts, the changeover between GridEngine and Slurm might be easy. There exists several "interoperability layers"  ... BiBiGrid installs one of them.

**Comment by a1an77** [comment]
Indeed we use the command line tools to interact with SGE. If the interoperability layer provide compatible interfaces to Slurm it might be seamless to switch, up to the cluster administration I guess. Anyway 2021 seems like a fair deadline, likely we would fully switch to an alternative by that date if OGE sill does not give life signs.
