### ISSUE TITLE
Line ending replacement command corrupts custom ansible role .tar.gz files

### ISSUE THREAD

**Issue by maitai** [BiBiServ/bibigrid#151]
The command
https://github.com/BiBiServ/bibigrid/blob/2c6559b1279a6f15233eca0b5dae447e741537c4/bibigrid-core/src/main/java/de/unibi/cebitec/bibigrid/core/util/ShellScriptCreator.java#L128-L129
potentially corrupts all `.tar.gz` files inside the `playbook/` directory on the master node by replacing all occurences of `0x0d0a` (\r\n) with `0x0a` (\n) in those files even before they have been extracted, resulting in corrupted gzip streams and incomplete custom ansible role directories.

##### Some ideas:
- The command-line tool `dos2unix` could be used instead of `sed` to prevent this type of modification of binary files in general:
```
$ dos2unix text.txt
dos2unix: converting file text.txt to Unix format...
$ dos2unix example_role.tar.gz
dos2unix: Binary symbol 0x1F found at line 1
dos2unix: Skipping binary file example_role.tar.gz
```
- Uploaded playbook `.tar.gz` files could be placed inside `/tmp/`

**Comment by jkrue** [comment]
Role archives (`*.tgz`, `.tar.gz`) should be uploaded to `/tmp/` instead to the playbook folder. The `sed` command should be only be executed on text files. Using `dos2unix` is of course an option, but the corresponding package must be installed beforehand manually.
