### ISSUE TITLE
Split properties files

### ISSUE THREAD

**Issue by pbelmann** [BiBiServ/bibigrid#16]
In my opinion the current properties file should be split in configuration.properties and credentials.properties.
This should make it easier to share property files without the fear of exposing the password.

I propose the following parameter:

``` BASH
-cr  credentials.properties | [--username <arg>, --password <arg>]
```

where

``` BASH
username=user
password=xxxxxx
```
- This parameter would be not mandatory, which means that the current configuration file containing username and password would still work. 
- If both configuration files are provided (-cr and -o) and both files contain a password and a user, the file provided by -cr will be used.
- On the long run it could replace the parameters:

``` BASH
-osp,--openstack-password <arg>
-osu,--openstack-username <arg>
-a,--aws-credentials-file <arg> 
```

If we agree on this, I can set up a PR.
If there is already a way to separate configuration details from credentials, then please close this issue.

**Comment by asczyrba** [comment]
I would suggest to remove at least the password option from the command line call. Otherwise it would be easy to get access to other people's passwords just by looking at running jobs. The password should only appear in the properties file, or it should be entered interactively on the command line on request.

**Comment by asczyrba** [comment]
Otherwise I agree that splitting credentials and options is a good idea!

**Comment by AstrorEnales** [comment]
There is now a single "--credentials-file string", "-cf string", "credentialsFile: string" parameter merging the paths to the aws, google and azure credentials files. The Openstack credentials can be provided just like before, but a separate yaml file can be used, too.
