### ISSUE TITLE
SLURM cluster nodes don't have as much RAM as their config indicates

### ISSUE THREAD

**Issue by nkleinbo** [BiBiServ/bibigrid#178]
I started a bibigrid cluster with machines having 16GB RAM, which is reduced to 15.66GB after booting. "scontrol show nodes" lists the nodes as having 16GB of RAM. When submitting jobs with the genome assembler canu, jobs that require 16GB of RAM are started (canu automatically checks for available resources), and fail, because only 15.66GB are available. Is there a way to specify the correct amount of RAM for the cluster nodes?

**Comment by jkrue** [comment]
> Is there a way to specify the correct amount of RAM for the cluster nodes?
The current worker configuration is generated when the cluster is initialized. All metadata (like memory size) is copied from the used flavor. It should be possible to  read the real memory using ansible facts. I will check this.

**Comment by jkrue** [comment]
Currently worker nodes are configured as :
`NodeName={{ worker.hostname }} ... RealMemory={{ worker.memory }} ...`

This however do not reserve any memory for the OS.  I decide to try the following configuration:

| worker.memory | slurm RealMemory option       |
|---------------|-------------------------|
| < 16 GB       | worker.memory - 512 MB  |
| >= 16 GB      | worker.memory - 1024 MB |

**Comment by jkrue** [comment]
fixed

**Comment by jkrue** [comment]
We noticed that the calculation of free real memory seems to be wrong for larger worker instances (> 64 GB RAM). We should also distinguish between master (using as worker) and worker nodes. I suggest the following configuration for the master:
```
RealMemory={{ mem - [mem // 2, 16000] | min }}
```
and the worker:
```
RealMemory={% if mem < 16000 %}{{ mem - [ mem // 16, 512] | max }}{% endif %}{% if mem > 16000 %}{{ mem - [mem // 16, 4000] | min }}{% endif %}
```
