### ISSUE TITLE
Openstack Application Credentials

### ISSUE THREAD

**Issue by ttubb** [BiBiServ/bibigrid#182]
I have problems setting up bibigrid in an openstack project, presumably because of invalid openstack credentials.
> ERROR: Connection failed: Unauthorized. Please make sure the supplied OpenStack credentials are valid. [StartUp:224]

Since i do not have a local password for my elixir ID, i have created application credentials in my OpenStack project. I have provided the corresponding ID and secret in the bibigrid credentials .yml-file, which looks like this:
```
username: 9dc[...]c73
projectName: NanoporeCWL
projectDomain: elixir 
domain: elixir  
password: _pB[...]U-A
endpoint: https://openstack.cebitec.uni-bielefeld.de:5000/v3
```
The openstack command line client works fine with the application credentials. Trying to run bibiserv results in the error shown above. Can i only run bibiserv with my elixir ID and not with application credentials? Or have i made mistakes in the configuration?

Regards,
Tom

**Comment by jkrue** [comment]
Dear Tom,

I have never tested Bibigrid with the ApplcationsCredentials before, but  I got the same error as you.
Seems that the underlying API doesn’t support ApplicationCredentials yet.

However we can set a password for your elixir account. Just come along my office (M3-120) on Thursday/Friday.

Best Jan

> On 18. Sep 2019, at 14:47, ttubb <notifications@github.com> wrote:
> 
> I have problems setting up bibigrid in an openstack project, presumably because of invalid openstack credentials.
> 
> ERROR: Connection failed: Unauthorized. Please make sure the supplied OpenStack credentials are valid. [StartUp:224]
> 
> Since i do not have a local password for my elixir ID, i have created application credentials in my OpenStack project. I have provided the corresponding ID and secret in the bibigrid credentials .yml-file, which looks like this:
> 
> username: 9dc[...]c73
> projectName: NanoporeCWL
> projectDomain: elixir
> domain: elixir
> password: _pB[...]U-A
> endpoint: https://openstack.cebitec.uni-bielefeld.de:5000/v3
> 
> The openstack command line client works fine with the application credentials. Trying to run bibiserv results in the error shown above. Can i only run bibiserv with my elixir ID and not with application credentials? Or have i made mistakes in the configuration?
> 
> Regards,
> Tom
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

---
Jan Krüger

Bielefeld University Bioinformatics Server (BiBiServ)
Center for Biotechnology (CeBiTec)

Bielefeld University
Faculty of Technology
33594 Bielefeld,Germany

room    : M3-120
phone  : +49 (521) 106 2494

**Comment by jkrue** [comment]
Unfortunately application credentials are currently not supported by the underlying Openstack framework ([Openstack4j](http://openstack4j.com)).
