### ISSUE TITLE
Support ansibleRole config file upload through REST Api 

### ISSUE THREAD

**Issue by timnrose** [BiBiServ/bibigrid#192]
In order to have full support for the bibigrid rest api there are some changes necessary because the file upload from command line and rest api is different.

Adjustments need to be made to the following two cluster configuration attribute
- ansibleRoles: vars_file: string
- ansibleGalaxyRoles: vars_file: string
to support the file upload through api.

**Comment by jkrue** [comment]
MR #248 fix this
