### ISSUE TITLE
Add support for Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#228]
Ubuntu 20.04 LTS will be released at the end of April. We should test BiBiGrid against it.

**Comment by tdilger** [comment]
At the moment the apt task fails, because the release file for Ubuntu 20.04 LTS focal is not available to add docker repository, yet. According to [askubuntu](https://askubuntu.com/questions/1230189/how-to-install-docker-community-on-ubuntu-20-04-lts) the solution right now is to use bionic instead, comment out focal in /etc/apt/sources.list and adjust the apt yml; already tested.

**Comment by tdilger** [comment]
Zabbix didn't work out because of ```deb: 'https://repo.zabbix.com/zabbix/4.0/{{ ansible_distribution | lower }}/pool/main/z/zabbix-release/zabbix-release_4.0-2+{{ ansible_distribution_release }}_all.deb'```. Changing [zabbix-release](https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/) to zabbix-release_4.0-3 fixed the issue and should last for longer.

**Comment by jkrue** [comment]
> At the moment the apt task fails, because the release file for Ubuntu 20.04 LTS focal is not available to add docker repository, yet. According to [askubuntu](https://askubuntu.com/questions/1230189/how-to-install-docker-community-on-ubuntu-20-04-lts) the solution right now is to use bionic instead, comment out focal in /etc/apt/sources.list and adjust the apt yml; already tested.

I add a switch for Ubuntu 20.04  in the corresponding task (fix/#228).

**Comment by jkrue** [comment]
> Zabbix didn't work out because of `deb: 'https://repo.zabbix.com/zabbix/4.0/{{ ansible_distribution | lower }}/pool/main/z/zabbix-release/zabbix-release_4.0-2+{{ ansible_distribution_release }}_all.deb'`. Changing [zabbix-release](https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/) to zabbix-release_4.0-3 fixed the issue and should last for longer.

The latest development branch already using Zabbix 4.4-1, which is available for all current LTS releases (16.04, 18.04 and 20.04)

**Comment by tdilger** [comment]
The template slurm.conf uses deprecated parameter "FastSchedule=2" which seem to collide with Ubuntu 20.04. According to [description](https://slurm.schedmd.com/slurm.conf.html) the alternative would be SlurmdParameters config_overrides

**Comment by jkrue** [comment]
A lot of minor problems are fixed concerning this issue. 

| OS | Version | Tested configuration | Support until | 
| --- | ------- | -------------------- | ----------- |
| Ubuntu | 20.04 | SLURM + Zabbix 5.0 + TheiaIDE 0.13 | 04/2025 |
| Ubuntu | 18.04 | SLURM + Zabbix 5.0 + TheiaIDE 0.13 | 04/2023 |
| Ubuntu | 16.04 | SLURM + Zabbix 5.0 + TheiaIDE 0.13 | 04/2021 |
| Ubuntu | 16.04 | OGE + Ganglia | supported until 04/2021 | 04/2021 |
| Debian | 10 | SLURM + Zabbix 5.0 + TheiaIDE 0.13 | approx. 2022 |

**Comment by jkrue** [comment]
Ubuntu 20.04 seems to use a slightly different mechanism for unindented upgrade. Following [the suggestion](https://itsfoss.com/auto-updates-ubuntu/) works fine for all supported LTS releases.
