### ISSUE TITLE
Check for supported OS 

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#241]
We should check for supported OS during cluster initialisation. In the case of an unsupported OS the configuration process should be abborted. This feature should be enabled by a configuration option.

**Comment by ggabernet** [comment]
Hi, that'd be indeed really helpful. 
I was trying to set up a Bibigrid cluster with `centos` but that was not supported as it tried to use `apt-get` instead of `yum`. It took me a bit to find the error, so a list of supported OS and clearer error message would be great!
