### ISSUE TITLE
Developer Guide

### ISSUE THREAD

**Issue by pbelmann** [BiBiServ/bibigrid#25]
@maitai  and I worked on a developer guide draft:
### Development workflow

Bibigrid development should follow the [github flow](https://guides.github.com/introduction/flow/)
which means that features or fixes should be pushed into a separate branch and merged into the master or development branch by creating a pull request. 

This should allow us to organize code reviews and automated tests before updating the development/master branch.   
### Branches

Pattern for branch names:

'refactor/name'
'feature/name'
'fix/name'

Feature branches should only be merged into the developer branch.
The master branch contains the code of the latest release.
### Releases

The release version names and tags should follow [semantic versioning](http://semver.org) 
### Commit Messages

Commit messages should follow the angular.js guide which allows to create automatically release summaries.

https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit

**Comment by jkrue** [comment]
Good work ... should place this somewhere in the project **README.md** file.

**Comment by pbelmann** [comment]
basic guide added (https://github.com/BiBiServ/Development-Guidelines)

@jkrue @maitai @asczyrba   please update/ if something is missing

**Comment by maitai** [comment]
We might even be able to _autogenerate_ every release changelog using a command-line tool called [clog](https://github.com/clog-tool/clog-cli) as long we follow [this convention](https://github.com/conventional-changelog/conventional-changelog/blob/a5505865ff3dd710cf757f50530e73ef0ca641da/conventions/angular.md).
