### ISSUE TITLE
use hostname instead of IP addresses in ansible_hosts file

### ISSUE THREAD

**Issue by asczyrba** [BiBiServ/bibigrid#275]
in a long running cluster, a VM or hypervisor might fail and need to be restarted manually. In these cases the IP address might change. This causes trouble when deploying software using the original ansible_hosts file which includes IP addresses instead of hostnames

Would it be possible to use hostnames instead of IP addresses?

**Comment by jkrue** [comment]
It's possible, but it prerequisites that DNS resolving works for "local" hostnames. Unfortunately this is not the case for all de.NBI cloud sites. We add an option that allows the user to switch on this property, but default is to use IP addresses instead of hostnames.
