### ISSUE TITLE
Openstack implementation lacks support for Volumes/Snapshots

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#28]

**Comment by jkrue** [comment]
Lastest development branch supports now volumes/snapshots for the master instance. Volumes/Snapshots for slaves instances not supported yet ...

**Comment by jkrue** [comment]
Commit 9db887 fixes a bug that prevents BiBigrid to share a mounted volume as NFS.

**Comment by AstrorEnales** [comment]
Slave mounts will be removed and therefore this issue isn't relevant any more.
