### ISSUE TITLE
Allow to terminate more than one cluster per bibigrid call

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#30]
Currently the bibigrid **terminate** action supports only one argument (= cluster id to terminate). Sometimes it seems to be  useful to terminate more than one cluster with a single call (e.g. clean up after a workshop)

**Comment by AstrorEnales** [comment]
It's now possible to terminate multiple clusters with one call. The ids are passed just like before but joined by a "/".
Example:
> bibigrid -t id1/id2/id3
