### ISSUE TITLE
Zabbix database can be very large for a long running BiBiGrid

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#307]
When using  Zabbix as monitor tool the database used by Zabbix can be very large for long running  BiBiGrids.  The retention time for item data is currently set to Zabbix default. We should change it to a more data-saving configuration. As add-on it should be configurable!

**Comment by tdilger** [comment]
The [Zabbix Housekeeper](https://www.zabbix.com/documentation/current/manual/web_interface/frontend_sections/administration/general) (Section 3) seems to be the place to lookup. This should be enabled and set to a rational config in forehand.
