### ISSUE TITLE
Fail to mount /vol/spool volumes

### ISSUE THREAD

**Issue by ggabernet** [BiBiServ/bibigrid#310]
Hi @jkrue ,
thanks for the nice bibigrid tool, I've been able to setup a SLURM cluster on deNBI Bielefeld. Currently I'm trying it out in denBI Tübingen but I'm experiencing some problems on deNBI Tübingen, that seem to be related to mounting the shared nfs volume:

```
ERROR: Cluster configuration failed.
failed: [193.196.29.12] (item={'src': '/vol/spool', 'dst': '/vol/spool'}) => {"ansible_loop_var": "item", "changed": false, "item": {"dst": "/vol/spool", "src": "/vol/spool"}, "msg": "Error mounting /vol/spool: mount.nfs4: access denied by server while mounting 193.196.29.190:/vol/spool\n"} [CreateCluster:181]
de.unibi.cebitec.bibigrid.core.model.exceptions.ConfigurationException: Cluster configuration failed.
failed: [193.196.29.12] (item={'src': '/vol/spool', 'dst': '/vol/spool'}) => {"ansible_loop_var": "item", "changed": false, "item": {"dst": "/vol/spool", "src": "/vol/spool"}, "msg": "Error mounting /vol/spool: mount.nfs4: access denied by server while mounting 193.196.29.190:/vol/spool\n"}
	at de.unibi.cebitec.bibigrid.core.intents.CreateCluster.configureAnsible(CreateCluster.java:424)
	at de.unibi.cebitec.bibigrid.core.intents.CreateCluster.launchClusterInstances(CreateCluster.java:175)
	at de.unibi.cebitec.bibigrid.StartUp.runCreateIntent(StartUp.java:345)
	at de.unibi.cebitec.bibigrid.StartUp.runIntent(StartUp.java:250)
	at de.unibi.cebitec.bibigrid.StartUp.main(StartUp.java:145)
ERROR: Aborting operation. Instances already running. Attempting to shut them down but in case of an error they might remain running. Please verify afterwards. [StartUp:351]
```
The command I used for launching the cluster:
```
java -jar bibigrid-openstack-2.2.2.jar --version
v2.2.2 (Build: 2020-11-08T12:32:12Z)
java -jar bibigrid-openstack-2.2.2.jar -c -v -o template.yml
```
Please find attached the yml template that I used for the setup, I took into account the special settings for Tübingen in the template. I used the openrc file for authentication.

[template.txt](https://github.com/BiBiServ/bibigrid/files/6171366/template.txt)

**Comment by jkrue** [comment]
Seems to be a problem with the NFS-server. Please try to launch the cluster  with the debug option (-d) enabled and login into the master when the configuration fails (With enabled debug option bibigrid keeps a failed cluster running). 
- check if NFS server is running
- run ansible manually on master node; inside playbook folder run : `ansible-playbook -i <HOSTS_FILE> site.yml`

**Comment by ggabernet** [comment]
Hi @jkrue, 
thanks for the hint, I've run the cluster in debug mode and our sysadmin found the issue, the IP address range specificed in `/etc/exports` for `/vol/spool` was not sufficent to cover all nodes. Updating it to `193.196.29.0/25` solved the issue.

However in `debug` mode all nodes are down:
```
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
debug*       up   infinite      6  down* bibigrid-worker-1-1-...
```

So how can I solve this problem and successfully build a cluster?

**Comment by ggabernet** [comment]
I've figured out that there are multiple externa subnets in deNBI Tübingen, using the `denbi_uni_tuebingen_external2_subnet2` provided the correct IP range and the cluster was built without problems. 

Thanks again for your help @jkrue
