### ISSUE TITLE
Add clusters with SlurmDBD support

### ISSUE THREAD

**Issue by patricS4** [BiBiServ/bibigrid#331]
We are developing an autoscaling program that can be used to scale clusters automatically via Simple VM API.

A cluster configuration with [`SlurmDBD`](https://slurm.schedmd.com/slurmdbd.html) and [`pyslurm`](https://github.com/PySlurm/pyslurm.git) is required to retrieve job data and job history.

The resulting additional settings, such as influencing job priority with [`Multifactor Priority Plugin`](https://slurm.schedmd.com/priority_multifactor.html) and [`Trackable RESources`](https://slurm.schedmd.com/tres.html) may also be useful for other users.

##### slurm.conf
* `/etc/slurm-llnl/slurm.conf`
* `${HOME}/playbook/roles/common/templates/slurm/slurm.conf`
```console
ClusterName=bibigrid
AccountingStorageType=accounting_storage/slurmdbd
AccountingStoreJobComment=YES
```

##### slurmdbd `/etc/slurm-llnl/slurmdbd.conf`
```console
AuthType=auth/munge
AuthInfo=/var/run/munge/munge.socket.2
DbdHost=localhost
DebugLevel=info
StorageHost=localhost
StorageLoc=slurm_acct_db
StoragePass=DB_PASSWORD
StorageType=accounting_storage/mysql
StorageUser=slurm
LogFile=/var/log/slurm-llnl/slurmdbd.log
PidFile=/run/slurmdbd.pid
SlurmUser=slurm
```
##### mysql database
```console
mysql -u $user -p"$passsword" -Bse "create user 'slurm'@'localhost' identified by 'DB_PASSWORD';"
mysql -u $user -p"$passsword" -Bse "grant all on slurm_acct_db.* TO 'slurm'@'localhost';"
```

**Comment by jkrue** [comment]
#327 goes hand in hand with this issue.  The aim is to have an up-to-date slurm installed, which is independent of the underlying OS and also setup RESTAPI and Accounting.
