### ISSUE TITLE
can't use openstack application credentials

### ISSUE THREAD

**Issue by mr-c** [BiBiServ/bibigrid#341]
https://cloud.denbi.de/wiki/Compute_Center/Bielefeld/#application-credentials-use-openstack-api

**Comment by jkrue** [comment]
Dear Michael,

the current version of BiBiGrid is written in Java and uses Openstack4J to communicate with Openstack. Unfortunately, Openstack4J doesn't support application credentials, so you have to contact your cloud administrators in order for them to set an explicit local password (https://cloud.denbi.de/wiki/Compute_Center/Bielefeld/#note).

Just for information: We currently rewrite BiBiGrid using Python to support application credentials (among some other features which are not supported by Openstack4J).

Best Jan

**Comment by jkrue** [comment]
We prepare the launch of a python-based version of BiBiGrid. Therefore all issues concerning the java based version won't fix anymore.
