### ISSUE TITLE
BibiGrid setup fails at "Install Docker Community Edition"

### ISSUE THREAD

**Issue by vschnei** [BiBiServ/bibigrid#343]
Hi,

I struggling with setting up BibiGrid on the Berlin de.NBI node. 

Loading credentials worked fine, though during the deployment of the cluster the setup stops at:

TASK [common : Install Docker Community Edition]

The interactive process viewer (htop) shows that there is something going on.:
0.7% CPU and 320 MB Memory 

I have waited fo over 30 hours but nothing changed.

Do you have any idea? Suggestions?

**Comment by jkrue** [comment]
Did you try it another time? Stops the installation process at the same point? Which base image do you use (OS and Version) ?  Depending on your internet connection, the chosen flavors, and the underlying hardware the installation shouldn't take longer than 30-45 minutes

**Comment by jkrue** [comment]
We prepare the launch of a python-based version of BiBiGrid. Therefore all issues concerning the java based version won't fix anymore.
