### ISSUE TITLE
Add GPU information for slurm

### ISSUE THREAD

**Issue by patricS4** [BiBiServ/bibigrid#344]
Add GPU information for slurm, GPU workers cannot be identified at this time.

For example with [GRES](https://slurm.schedmd.com/gres.html#GPU_Management):

```
NodeName=bibigrid-worker-xy SocketsPerBoard=28 CoresPerSocket=1 RealMemory=496000 TmpDisk=4000000 Gres=gpu:2
```

**Comment by jkrue** [comment]
We prepare the launch of a python-based version of BiBiGrid. Therefore all issues concerning the java based version won't fix anymore.
