### ISSUE TITLE
Documentation of used software in markdown

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#350]
| Copied from [Gitlab](https://gitlab.ub.uni-bielefeld.de/bibiserv/bibigrid/bibigrid2/-/issues/25) | 
| --- |

It would be great to have more extensive documentation covering the software used by BiBiGrid (slurm, Ansible, ...). This should be done in markdown as part of the repository.

A few questions arose while thinking about the further documentation:

1. To what degree shall we document the software used in BiBiGrid? A reference to the original documentation is very helpful, but citing that documentation within the BiBiGrid documentation should be very sparse in order to avoid overloading the BiBiGrid documentation. I think only listing a few options within the BiBiGrid documentation should be enough.
2. To what degree shall we document the internal BiBiGrid processes? While explaining how to determine after-launch-cloud-provider-services in order to name them in the `bibigrid.yml` is very helpful for the common user, explaining how the ide port forwarding works is probably not. I think that only listing those internal processes that may directly affect the user experience is a good focus for now.

**Comment by XaverStiensmeier** [comment]
This issue hasn't sparked any discussion and is therefore closed until interest arises.
