### ISSUE TITLE
How to handle daemons on worker nodes?

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#351]
| Copied from [GitLab](https://gitlab.ub.uni-bielefeld.de/bibiserv/bibigrid/bibigrid2/-/issues/44) |
| --- |

Some users might want to run daemons on worker nodes. Daemons are started and stopped. Starting and stopping are short slurm jobs. Therefore slurm will terminate the node while the daemon is still running. It would be nice if a workflow can be explained to users to avoid this.

**Comment by XaverStiensmeier** [comment]
This issue will be closed and reopened once interest arises.
