### ISSUE TITLE
No auto-scaling after errors despite available resources

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#352]
| Copied from [GitLab](https://gitlab.ub.uni-bielefeld.de/bibiserv/bibigrid/bibigrid2/-/issues/45) |
| --- | 

At the beginning everything worked fine, every new job spawned a new instance. After some time errors happened in OpenStack, as instances could not be started. Slurm seems to not recognize these OpenStack errors and tries to allocate jobs to these machines. These jobs fail after some time and new jobs get submitted to these failed instances, and so forth so on. These loops can only be stopped by deleting these error instances by hand.

After that no new instances get spawned, despite me deleting old instances of the same size in my project. I also tried to start these instances by hand, this works. There is definitely enough space for these kind of instance in openstack, slurm just never asks again.

**Comment by XaverStiensmeier** [comment]
This should largely be fixed, but needs testing. Also a general overwork of instance failure should be done moving the entire error handling to the fail script. This solution would be much easier to maintain and handles varying exceptions more gracefully.

**Comment by XaverStiensmeier** [comment]
Closed as we do not get any reports mentioning auto-scaling breaking as long as the configuration is sound.
