### ISSUE TITLE
Slurm schedules jobs to inadequate nodes at times

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#353]
| Copied from [GitLab](https://gitlab.ub.uni-bielefeld.de/bibiserv/bibigrid/bibigrid2/-/issues/47) |
| --- |

It has been reported that slurm sometimes schedules jobs for inadequate nodes - i.e. the node is over-equipped and a fitting node with fewer resources has been available.

**Comment by XaverStiensmeier** [comment]
Closed as no info was brought up. As BiBiGrid has evolved a lot since 16.12.22 it is unsure whether this issue still persists. Reopen if reports mentioning inadequate scheduling occur.
