### ISSUE TITLE
Warn user if --cid contains a "-"

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#354]
| Copied from [GitLab](https://gitlab.ub.uni-bielefeld.de/bibiserv/bibigrid/bibigrid2/-/issues/48) |
| --- |

Sometimes users might accidentally copy the entire master name instead of just the cluster id. In that case, the program should either abort and hint the human error or still hint the human error but rescue the run.

**Comment by XaverStiensmeier** [comment]
Hinting the human error and rescuing the run is now implemented in #365

**Comment by jkrue** [comment]
fixed
