### ISSUE TITLE
More "dynamic" output

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#355]
| Copied from [GitLab](https://gitlab.ub.uni-bielefeld.de/bibiserv/bibigrid/bibigrid2/-/issues/56) |
| --- |

When creating a BiBiGrid cluster the output of any remote command is printed after it is finished. When a remote command takes a long time (like ansible), the user doesn't get any response if BiBiGrid is still working. Printing everything is possible to much information for a normal user, but we could print ansible messages starting with "[BiBiGrid]". However, an additional "quiet" mode should suppress any output.

**Comment by XaverStiensmeier** [comment]
This was basically implemented. If further implementation is needed (for example an explicit "quiet" mode; currently implicit by not using any verbose flags), this issue will be reopened.
