### ISSUE TITLE
slurmrestd service fails to start on ubuntu os

### ISSUE THREAD

**Issue by dgoebel97** [BiBiServ/bibigrid#356]
The REST API by slurm is started using a service with `systemctl` on ubuntu. The [documentation](https://slurm.schedmd.com/rest.html#local_auth) states that "By default, slurmrestd will not start as root or SlurmUser or if the user's primary group belongs to root or SlurmUser", This is the reason why the service fails to start with the following error message

```
bibigrid-master-7r0iegsmebvi2sd systemd[1]: Started Slurm REST daemon.
bibigrid-master-7r0iegsmebvi2sd slurmrestd[1578]: slurmrestd: fatal: slurmrestd should not be run as the root user.
bibigrid-master-7r0iegsmebvi2sd slurmrestd[1578]: fatal: slurmrestd should not be run as the root user.
bibigrid-master-7r0iegsmebvi2sd systemd[1]: slurmrestd.service: Main process exited, code=exited, status=1/FAILURE
bibigrid-master-7r0iegsmebvi2sd systemd[1]: slurmrestd.service: Failed with result 'exit-code'.
```

One fix could be to change the owner of the `slurmrestd` process to the `ubuntu` user. For that the file `resources/playbook/roles/bibigrid/files/slurm/slurmrestd_override.conf` has to be changed to

```
# Override systemd service ExecStart command to disable unixSocket of slurmrestd
[Unit]
After=slurmdbd.service
[Service]
ExecStart=
ExecStart=/usr/sbin/slurmrestd $SLURMRESTD_OPTIONS
User=ubuntu
Group=ubuntu
```

**Comment by jkrue** [comment]
fix with #367
