### ISSUE TITLE
Upgrade Slurm OpenAPI Plugin

### ISSUE THREAD

**Issue by dgoebel97** [BiBiServ/bibigrid#357]
The Version of the Slurm OpenAPI Plugin is fixed to `v0.0.36` but the installed Slurm Version (`21.8.5`) already supports the version `v0.0.37`. The next Slurm version `22.05.0` adds the new OpenAPI Plugin version `v0.0.38` and marks `v0.0.36` as deprecated. This information can be seen on the [Slurm OpenAPI Plugin Release Notes](https://slurm.schedmd.com/openapi_release_notes.html).

To use a newer version of the OpenAPI Plugin the environment variable `SLURMRESTD_OPENAPI_PLUGINS` in the file `resources/playbook/roles/bibigrid/files/slurm/slurmrestd_default`.   
You can find the explanation for this env variable in the documentation of the `slurmrestd` service: https://slurm.schedmd.com/slurmrestd.html#OPT_-s-%3COpenAPI-plugins-to-load%3E

**Comment by jkrue** [comment]
BiBiGrid runs Slurm version 22.05.6. Fixed with #367.
