### ISSUE TITLE
Adapt tests

### ISSUE THREAD

**Issue by XaverStiensmeier** [BiBiServ/bibigrid#359]
Since the last milestone's (clum) beginning tests have not really been updated due to prioritizing feature development speed (cloud scheduling, ...).
I've now temporarily deactivated pylint for tests, as they were unable to pass pylint's tests due too many unrelated violations after a simple import replacement. I think adapting tests and satisfying pylint is best done together.

**Comment by jkrue** [comment]
pylint is explicitly run on bibigrid folder. The test folder is currently not part of the lining job.
