### ISSUE TITLE
Add instances to dns

### ISSUE THREAD

**Issue by XaverStiensmeier** [BiBiServ/bibigrid#372]
dns server that uses all cloud dns' for resolution

**Comment by jkrue** [comment]
We will try dnsmasq as it is a relatively simple DNS- and DHCP-server for small networks.
1. Install dnsmasq : `apt install dnsmaq`  (possible on Ubuntu 20/22.04 and Debian 11)
2. stop & disable systemd-resolve 
3. configure & start dnsmaq

As we know, for now, only the master needs DNS resolving overall worker instances.

**Comment by jkrue** [comment]
Dnsmasq allows to bypassing of domains to a defined DNS.  
The configuration option ...
```
server=/intranet/10.17.1.1
```
... ask the DNS (10.17.1.1) for any requests according to the (top-level) domain *.intranet.
This feature might be helpful if it is possible to have different domains for different locations.

**Comment by jkrue** [comment]
#380 adds support for dnsmasq and config option for a list of external DNS server. 
- Documentation is missing
- vpn-worker must be added to dnsmasq.hosts 
- scale up and scale down script must add/remove created/terminated entries

**Comment by jkrue** [comment]
fixed
