### ISSUE TITLE
Errors in BiBiGrid documentation for slurm

### ISSUE THREAD

**Issue by dgoebel97** [BiBiServ/bibigrid#387]
In the documentation for Slurm  in the file [documentation/markdown/software/slurm.md](https://github.com/BiBiServ/bibigrid/blob/master/documentation/markdown/software/slurm.md#rest-api) in the section "REST API" are two errors

1. `slurmrestd` listen on the port `6820` for connections and not on `6420`
2. The command to create a JWT token should be
```
sudo scontrol token username=slurm [lifespan=<time in seconds>]
```

**Comment by XaverStiensmeier** [comment]
Thank you! This is now fixed in `dev`. I still need to work over some other things before everything new will be pushed to master.
