### ISSUE TITLE
[Hybrid-Coud] Don't use the VPN-GW as slurm node.

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#389]
In the current approach for a Hybrid-Cloud, the VPN-Gateway is configured as a SLURM worker/node. Since the GW instance should have a small resource footprint (using a tiny flavor with 1/2 cores and 2-4 GB RAM)  this doesn't make much sense.

**Comment by XaverStiensmeier** [comment]
This is implemented on dev now.
