### ISSUE TITLE
Zabbix can't contact foreign nodes (multi-cloud)

### ISSUE THREAD

**Issue by XaverStiensmeier** [BiBiServ/bibigrid#394]
Currently zabbix will mark all foreign nodes as not available. In the spirit of abstraction allowing zabbix to recognize those nodes without any further user inputs would be great.

**Comment by jkrue** [comment]
Another problem is that dynamically allocated workers have changing local IP addresses, making it (practically) impossible to assign them in Zabbix. In Zabbix, the assignment of hosts is done via IP address and not by name. Therefore, as soon as a host is terminated, it must be removed from the list of Zabbix hosts.

**Comment by XaverStiensmeier** [comment]
Maybe we can avoid this issue by using hostnames instead of ips: https://www.zabbix.com/documentation/2.0/en/manual/appendix/config/zabbix_agentd 

> Server: List of comma delimited IP addresses (or hostnames) of Zabbix servers.

**Comment by jkrue** [comment]
We already set the hostname:

```
### Option: Hostname
#	Unique, case sensitive hostname.
#	Required for active checks and must match hostname as configured on the server.
#	Value is acquired from HostnameItem if undefined.
#
# Mandatory: no
# Default:
# Hostname=
Hostname={{ ansible_hostname }}
```
On the server side, the hosts are still identified by IP address (and not by name).

**Comment by XaverStiensmeier** [comment]
This could be also worth a try: https://www.zabbix.com/documentation/current/en/manual/discovery/auto_registration#using-dns-as-default-interface
