### ISSUE TITLE
BibiGrid Logging

### ISSUE THREAD

**Issue by pbelmann** [BiBiServ/bibigrid#4]
- Add multiple logging level (etc. INFO, ALL, DEBUG ).
- On Debug level the stacktrace should also be printed and not only message:

Example:

```
ERROR: null [CreateClusterOpenstack:336]
ERROR: Aborting operation. Instances already running. I will try to shut them down but in case of an error they might remain running. Please check manually afterwards. [CreateIntent:41]
```

Originates from:

https://github.com/BiBiServ/bibigrid/blob/master/src/main/java/de/unibi/cebitec/bibigrid/meta/openstack/CreateClusterOpenstack.java#L336-L336

**Comment by tdilger** [comment]
Implemented between 2016-2018: 
1. Command line option verbose: -v
     - print out every single task
2. Configuration options: debugRequest 
      - print out request response messages between bibigrid and cloud api
3. Error handling
