### ISSUE TITLE
Master post configuration hangs if slave instances not reachable ...

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#43]
Sometimes it could happen that a started cluster instance can't be reached for some reason. In that case the master post configuration hangs forever ... we should integrate a timeout !

**Comment by jkrue** [comment]
- the timeout value should be adjustable via cmdline options with an appropriate default value (e.g. 2 minutes). 
- Instances that could be configured should be shutdown afterwards ...

**Comment by AstrorEnales** [comment]
With Ansible the situation has changed. How does ansible handle unresponsive instances? Is this still necessary?

**Comment by jkrue** [comment]
You're right, the situation changed completely with ansible. We could close this issue!
