### ISSUE TITLE
Startup of slave instances seems NOT be run in parallel

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#50]
This bug currently affects only OpenStack

**Comment by AstrorEnales** [comment]
Merge structure of instance startup from Google compute engine to base class for all providers

**Comment by AstrorEnales** [comment]
The slave instances are run in parallel. Since the implementation of slave type batches, the batches are run sequentially for all providers. This needs to be solved in the base class for all providers.
