### ISSUE TITLE
Restructuring 

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#56]
The current layout does not fit our needs anymore. We should separate the model  and the general parts from the framework from the cloud specific implementations (AWS, Google, Openstack, ... ). The general configuration of the grid is currently hard coded, which is fast  (while executed) but  awful to extend and fix. This will be replaced by an Ansible setup in near future ( issue #47) 

Here is a 1st idea for a preliminary structure:

```
/ansible
/model
  /exceptions
/intents
/aws
/google
/openstack
```

We should implement unit tests for *all* external functions and  use an continuous testing/integration framework.

**Comment by AstrorEnales** [comment]
The code base is restructured. For further enhancements like unit tests, etc. we should open seperate and more granular issues.
