### ISSUE TITLE
Early execute scripts in combination with ansible

### ISSUE THREAD

**Issue by AstrorEnales** [BiBiServ/bibigrid#58]
@jkrue As discussed before, it's maybe a good idea to move the early execute scripts from the metadata of the instance to the ansible process.
This would...
- ensure everything is setup
- remove the limit of 10000 base64 characters
- windows azure doesn't even support metadata scripts

Also in this context, there are currently three options...
- early-execute-script
- early-slave-execute-script
- execute-script
where execute-script would basically do the same on the master. So this could probably be removed?

**Comment by jkrue** [comment]
@AstrorEnales I aggree in removing:

- early-execute-script
- early-slave-execute-script
- execute-script

Instead we have to add an option to execute own ansible scripts.
