### ISSUE TITLE
Evaluate web interface possibilities

### ISSUE THREAD

**Issue by AstrorEnales** [BiBiServ/bibigrid#59]
Evaluate the idea for a user friendly web interface

**Comment by jkrue** [comment]
A year later ... we had again a discussion about creating a user friendly web interface on top of BiBiGrid. However, this needs a restructuring/extending of the source tree. BiBiGrid currently works as standalone application, to build a web application on top of it we need:
- a (REST) API 
- a user management 
- a web server 
- ...

**Comment by jkrue** [comment]
BiBiGrid needs some configuration changes to establish an API on the top of the current implementation.  With the solution for #181 (one-time keypair) there is no need to transfer a private key (bad idea) to the REST API anymore. The current implementation only supports adding one public key (from a file). We should adjust the configuration to support a list of public keys, but this might be an incompatible configuration change.

**Comment by jkrue** [comment]
MR #248 integrates a REST API for BiBiGrid. The API is used by the portal to offer an user friendly WEB UI for BiBiGrid.
