### ISSUE TITLE
Create template image to decrease bibigrid startup time 

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#67]
We have currently the problem that  bibigrid starts with blank Ubuntu images. Everything needed is installed during the ansible run. That causes two problems:
- high startup time
- high network load (each slave get all packages)

We can avoid this, when using prepared images. Workflow to create prepared images:
- start two (small) instances (master + slave)
- run ansible with additional -t install argument
- clean up instances -> (we could write an ansible task for this :-) 
- snapshot instances

**Comment by jkrue** [comment]
this is somehow related to #13

**Comment by AstrorEnales** [comment]
Clean up of instances should possibly include:
- remove ssh keys where possible (especially since google compute adds the keys that are present in metadata keys)
- Remove ssh user home folder (is this possible while being logged in as this user during ansible run?)

**Comment by jkrue** [comment]
This issue will not fixed.
