### ISSUE TITLE
Add SLURM support

### ISSUE THREAD

**Issue by AstrorEnales** [BiBiServ/bibigrid#79]
Add SLURM support

**Comment by jkrue** [comment]
Up today it is not clear if SLURM is a good replacement for the [S]GridEngine. However, since it seems that GridEngine is not longer maintained actively and the current OS (Ubuntu 18.04) comes with dependencies problems (broken packages), we have to find a suitable alternative.

**Comment by jkrue** [comment]
The branche feature/slurmtask adds base slurm support. Before closing this task we have think about adding a SGE compatible layer. https://github.com/mauranolab/sge2slurm seems to be worth a try.
