### ISSUE TITLE
Startup of openstack jar causes instant NullpointerException.

### ISSUE THREAD

**Issue by awalende** [BiBiServ/bibigrid#80]
I'm not able to run the bibigrid-openstack jar.
I have build it with:
`mvn -P openstack clean package`
There were no errors building it.

Every startup option crashes with a NullPointerException:
`awalende@awalende-Aspire-E5-571 ~/bibigrid/bibigrid-main/target $ java -jar bibigrid-openstack-2.0.jar -ch -o ~/.bibigrid.yml
Ok : Alternative config file /home/awalende/.bibigrid.yml will be used.
Exception in thread "main" java.lang.NullPointerException
	at de.unibi.cebitec.bibigrid.StartUp.parseProviderMode(StartUp.java:252)
	at de.unibi.cebitec.bibigrid.StartUp.runIntent(StartUp.java:146)
	at de.unibi.cebitec.bibigrid.StartUp.main(StartUp.java:107)
`

My JRE is:
`java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)`

**Comment by AstrorEnales** [comment]
Thanks for the report. It seems you didn't provide a value for the "mode" parameter in command line or properties file. It's a bit counter intuitive for this to be necessary when the jar is openstack specific.
I will add a check and proper error message for this case. But until then, just add the "mode: openstack" in your yaml config file and it should work fine.
