### ISSUE TITLE
Gridengine does not get started

### ISSUE THREAD

**Issue by asczyrba** [BiBiServ/bibigrid#82]
I tried to spin up a cluster on Openstack, but I do not get a cluster with a gridengine installed. I tried both the master and development branch with Ubuntu 16.04 and 18.04 images without success

**Comment by AstrorEnales** [comment]
It was a bug introduced with the last fix for NFS mounts. If no disks were mounted to the master, ansible threw an error.
I fixed the bug and everything works fine again. Please currently use the master branch (All progress and bugfixes are there). Additionally i added a new log message if ansible errors occur, so in the future, these should be more clear to the end user if not running in verbose mode.

**Comment by asczyrba** [comment]
Still does not work, I get the following error message:

```ubuntu@bibigrid-master-nwo1zu9rvuorauu:~$ qhost
error: unable to read qmaster name: qmaster hostname in "/var/lib/gridengine/default/common/act_qmaster" has zero length
```

**Comment by AstrorEnales** [comment]
In my test today, everything worked fine and the qmaster hostname was generated correctly. I assume something must have gone wrong with the nslookup on your master?
Which network and region/zone do you use?
@jkrue Jan, do you have an idea what could be wrong here?

**Comment by asczyrba** [comment]
Which Ubuntu version did you use? 16.04?

**Comment by AstrorEnales** [comment]
Yes, the currently active 16.04 with id "c1ac4343-cc53-4827-a3bf-9fdde2a67c8c".

**Comment by asczyrba** [comment]
works fine with Ubuntu 16.04
