### ISSUE TITLE
Error during volume mounting

### ISSUE THREAD

**Issue by andreashoek** [BiBiServ/bibigrid#84]
Mounting of volume (specified in bibigrid.yml -> masterMounts) to cluster in OpenStack during BiBiGrid startup fails with:

`SSH: Task [master: mount disks] ***********************************************************
 SSH: failed: [localhost] (item={u'src': u'/dev/vdb', u'dst': u'/asap'}) => {"changed": false, "item": {"dst": "/asap/", "src": "/dev/vdb"}, "msg": "Error mounting /asap/: mount: wrong fs type, bad option, bad superblock on /dev/vdb missing codepage or helper program, or other error\n\n    In some cases useful info is found in syslog - try\n   dmesg | tail or so.\n"}  to retry, use: --limit @/home/ubuntu/playbook/site.retry`

**Comment by jkrue** [comment]
I can confirm this error. The difference to other cloud sites is that Giessen offers so-called config drives. For some reasons the switch for using config-drives is interpreted in a wrong way.
